# Generated by Django 5.2.4 on 2025-08-30 09:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_revieweating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewEating',
            new_name='ReviewRating',
        ),
    ]
