# Generated by Django 5.2.4 on 2025-08-31 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_revieweating_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='reting',
            new_name='rating',
        ),
    ]
