# Generated by Django 5.2.4 on 2025-08-31 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_reting_reviewrating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='Product',
            new_name='product',
        ),
    ]
