# Generated by Django 5.2.4 on 2025-09-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_2',
            new_name='address2',
        ),
    ]
