# Generated by Django 5.2.4 on 2025-08-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
